include:
  - component: $CI_SERVER_FQDN/ci-components/gitflow-hooks/node@1.0.0
    inputs:
      git_user: '$GIT_ACCESS_USER'
      git_pass: '$GIT_ACCESS_PASSWORD'
      tag: 'fast'
  - component: $CI_SERVER_FQDN/ci-components/changelog/cliff-wild@1.0.2
    inputs:
      tag: fast

  - component: $CI_SERVER_FQDN/ci-components/vendure/publish-module@2.0.0
    inputs:
      npm-registery-token: "${NPM_REGISTERY_TOKEN}"

  - component: $CI_SERVER_FQDN/ci-components/vendure/publish-module-public@2.0.0
    inputs:
      npm-registery-token: "${PUBLIC_NPM_REGISTERY_TOKEN}"
      github-repository: "github:datasolution-oss/vendure-pricelist-plugin"
      github-homepage: "https://github.com/datasolution-oss/vendure-pricelist-plugin#readme"


stages:
  - versioning
  - build
  - changelog
  - release